// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: valueprocs/proto/valueprocs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	proc "sigmaos/proc"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RunRef names one attempt at one leaf.
//
// All three fields travel together everywhere, because a leaf that is stopped
// runs again under a higher run number. Without it, a message about an
// attempt that has already been superseded is indistinguishable from one
// about the current attempt, and would be applied to the wrong one instead of
// dropped.
type RunRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TID    string `protobuf:"bytes,1,opt,name=tID,proto3" json:"tID,omitempty"`
	NodeID string `protobuf:"bytes,2,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Run    uint64 `protobuf:"varint,3,opt,name=run,proto3" json:"run,omitempty"`
}

func (x *RunRef) Reset() {
	*x = RunRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valueprocs_proto_valueprocs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRef) ProtoMessage() {}

func (x *RunRef) ProtoReflect() protoreflect.Message {
	mi := &file_valueprocs_proto_valueprocs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRef.ProtoReflect.Descriptor instead.
func (*RunRef) Descriptor() ([]byte, []int) {
	return file_valueprocs_proto_valueprocs_proto_rawDescGZIP(), []int{0}
}

func (x *RunRef) GetTID() string {
	if x != nil {
		return x.TID
	}
	return ""
}

func (x *RunRef) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

func (x *RunRef) GetRun() uint64 {
	if x != nil {
		return x.Run
	}
	return 0
}

// NodeSpec is one node of a submitted tree, recursively. A node with no
// children is a leaf and carries a proc; a node with children is a k-of-n
// select and carries k.
//
// Node identity is deliberately absent. The scheduler derives it from the
// node's position in the tree, so that two clients cannot disagree about what
// a name means; a client that wants to recognise a node in a report gives it
// a label instead.
type NodeSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	K        int32           `protobuf:"varint,1,opt,name=k,proto3" json:"k,omitempty"`
	Children []*NodeSpec     `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	LeafProc *proc.ProcProto `protobuf:"bytes,3,opt,name=leafProc,proto3" json:"leafProc,omitempty"` // set iff children is empty
	Label    string          `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
}

func (x *NodeSpec) Reset() {
	*x = NodeSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valueprocs_proto_valueprocs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSpec) ProtoMessage() {}

func (x *NodeSpec) ProtoReflect() protoreflect.Message {
	mi := &file_valueprocs_proto_valueprocs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSpec.ProtoReflect.Descriptor instead.
func (*NodeSpec) Descriptor() ([]byte, []int) {
	return file_valueprocs_proto_valueprocs_proto_rawDescGZIP(), []int{1}
}

func (x *NodeSpec) GetK() int32 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *NodeSpec) GetChildren() []*NodeSpec {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *NodeSpec) GetLeafProc() *proc.ProcProto {
	if x != nil {
		return x.LeafProc
	}
	return nil
}

func (x *NodeSpec) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// SubmitTreeReq registers a tree.
//
// The caller chooses tID, and resubmitting one that is already registered is
// an error rather than a second tree. That is what makes a submission safe to
// retry over a connection that may have dropped after the service acted.
//
// The attributes an arbiter divides capacity on are not here on purpose. They
// come from the identity of the caller, which the service reads from the RPC
// itself, so that an application cannot raise its own share by describing
// itself generously.
type SubmitTreeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TID   string    `protobuf:"bytes,1,opt,name=tID,proto3" json:"tID,omitempty"`
	Label string    `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Root  *NodeSpec `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
}

func (x *SubmitTreeReq) Reset() {
	*x = SubmitTreeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valueprocs_proto_valueprocs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitTreeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTreeReq) ProtoMessage() {}

func (x *SubmitTreeReq) ProtoReflect() protoreflect.Message {
	mi := &file_valueprocs_proto_valueprocs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTreeReq.ProtoReflect.Descriptor instead.
func (*SubmitTreeReq) Descriptor() ([]byte, []int) {
	return file_valueprocs_proto_valueprocs_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitTreeReq) GetTID() string {
	if x != nil {
		return x.TID
	}
	return ""
}

func (x *SubmitTreeReq) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SubmitTreeReq) GetRoot() *NodeSpec {
	if x != nil {
		return x.Root
	}
	return nil
}

type SubmitTreeRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TID string `protobuf:"bytes,1,opt,name=tID,proto3" json:"tID,omitempty"`
}

func (x *SubmitTreeRep) Reset() {
	*x = SubmitTreeRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valueprocs_proto_valueprocs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitTreeRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTreeRep) ProtoMessage() {}

func (x *SubmitTreeRep) ProtoReflect() protoreflect.Message {
	mi := &file_valueprocs_proto_valueprocs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTreeRep.ProtoReflect.Descriptor instead.
func (*SubmitTreeRep) Descriptor() ([]byte, []int) {
	return file_valueprocs_proto_valueprocs_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitTreeRep) GetTID() string {
	if x != nil {
		return x.TID
	}
	return ""
}

type CancelTreeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TID string `protobuf:"bytes,1,opt,name=tID,proto3" json:"tID,omitempty"`
}

func (x *CancelTreeReq) Reset() {
	*x = CancelTreeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valueprocs_proto_valueprocs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelTreeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTreeReq) ProtoMessage() {}

func (x *CancelTreeReq) ProtoReflect() protoreflect.Message {
	mi := &file_valueprocs_proto_valueprocs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTreeReq.ProtoReflect.Descriptor instead.
func (*CancelTreeReq) Descriptor() ([]byte, []int) {
	return file_valueprocs_proto_valueprocs_proto_rawDescGZIP(), []int{4}
}

func (x *CancelTreeReq) GetTID() string {
	if x != nil {
		return x.TID
	}
	return ""
}

type CancelTreeRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OK bool `protobuf:"varint,1,opt,name=oK,proto3" json:"oK,omitempty"`
}

func (x *CancelTreeRep) Reset() {
	*x = CancelTreeRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valueprocs_proto_valueprocs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelTreeRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTreeRep) ProtoMessage() {}

func (x *CancelTreeRep) ProtoReflect() protoreflect.Message {
	mi := &file_valueprocs_proto_valueprocs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTreeRep.ProtoReflect.Descriptor instead.
func (*CancelTreeRep) Descriptor() ([]byte, []int) {
	return file_valueprocs_proto_valueprocs_proto_rawDescGZIP(), []int{5}
}

func (x *CancelTreeRep) GetOK() bool {
	if x != nil {
		return x.OK
	}
	return false
}

// ReportScoreReq is pushed by a running proc, and is the hot path.
//
// score is opaque: higher means more deserving of resources, and only the
// ordering among one node's children carries any meaning. gradient is the
// marginal value of one more attempt racing the same goal, which is the
// extrapolation the scheduler is not allowed to infer from score.
type ReportScoreReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ref      *RunRef `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Score    float64 `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Gradient float64 `protobuf:"fixed64,3,opt,name=gradient,proto3" json:"gradient,omitempty"`
}

func (x *ReportScoreReq) Reset() {
	*x = ReportScoreReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valueprocs_proto_valueprocs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportScoreReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportScoreReq) ProtoMessage() {}

func (x *ReportScoreReq) ProtoReflect() protoreflect.Message {
	mi := &file_valueprocs_proto_valueprocs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportScoreReq.ProtoReflect.Descriptor instead.
func (*ReportScoreReq) Descriptor() ([]byte, []int) {
	return file_valueprocs_proto_valueprocs_proto_rawDescGZIP(), []int{6}
}

func (x *ReportScoreReq) GetRef() *RunRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *ReportScoreReq) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ReportScoreReq) GetGradient() float64 {
	if x != nil {
		return x.Gradient
	}
	return 0
}

type ReportScoreRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OK bool `protobuf:"varint,1,opt,name=oK,proto3" json:"oK,omitempty"`
}

func (x *ReportScoreRep) Reset() {
	*x = ReportScoreRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valueprocs_proto_valueprocs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportScoreRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportScoreRep) ProtoMessage() {}

func (x *ReportScoreRep) ProtoReflect() protoreflect.Message {
	mi := &file_valueprocs_proto_valueprocs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportScoreRep.ProtoReflect.Descriptor instead.
func (*ReportScoreRep) Descriptor() ([]byte, []int) {
	return file_valueprocs_proto_valueprocs_proto_rawDescGZIP(), []int{7}
}

func (x *ReportScoreRep) GetOK() bool {
	if x != nil {
		return x.OK
	}
	return false
}

// LeafResult is one leaf's finished output.
type LeafResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq        uint64  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"` // position in its tree's log, from 1
	Ref        *RunRef `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	Label      string  `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	ProcStatus []byte  `protobuf:"bytes,4,opt,name=procStatus,proto3" json:"procStatus,omitempty"` // proc.Status.Marshal()
}

func (x *LeafResult) Reset() {
	*x = LeafResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valueprocs_proto_valueprocs_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeafResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeafResult) ProtoMessage() {}

func (x *LeafResult) ProtoReflect() protoreflect.Message {
	mi := &file_valueprocs_proto_valueprocs_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeafResult.ProtoReflect.Descriptor instead.
func (*LeafResult) Descriptor() ([]byte, []int) {
	return file_valueprocs_proto_valueprocs_proto_rawDescGZIP(), []int{8}
}

func (x *LeafResult) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *LeafResult) GetRef() *RunRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *LeafResult) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *LeafResult) GetProcStatus() []byte {
	if x != nil {
		return x.ProcStatus
	}
	return nil
}

// NextResultsReq asks for everything a tree produced after a position the
// caller holds. The service keeps no per-reader state, so the same request
// twice returns the same answer and one that fails halfway may simply be made
// again.
type NextResultsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TID   string `protobuf:"bytes,1,opt,name=tID,proto3" json:"tID,omitempty"`
	Since uint64 `protobuf:"varint,2,opt,name=since,proto3" json:"since,omitempty"`
	// epoch identifies the incarnation of the service the caller's position
	// came from. Zero asserts nothing, which is what a first read sends;
	// anything else is checked, because the numbering restarts when the
	// service does and a stale position would otherwise be answered with a
	// different result wearing the same sequence number.
	Epoch uint64 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// waitMs parks the call until something lands, the tree finishes, or the
	// wait elapses. Zero returns whatever is available immediately.
	WaitMs int64 `protobuf:"varint,4,opt,name=waitMs,proto3" json:"waitMs,omitempty"`
}

func (x *NextResultsReq) Reset() {
	*x = NextResultsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valueprocs_proto_valueprocs_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NextResultsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextResultsReq) ProtoMessage() {}

func (x *NextResultsReq) ProtoReflect() protoreflect.Message {
	mi := &file_valueprocs_proto_valueprocs_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextResultsReq.ProtoReflect.Descriptor instead.
func (*NextResultsReq) Descriptor() ([]byte, []int) {
	return file_valueprocs_proto_valueprocs_proto_rawDescGZIP(), []int{9}
}

func (x *NextResultsReq) GetTID() string {
	if x != nil {
		return x.TID
	}
	return ""
}

func (x *NextResultsReq) GetSince() uint64 {
	if x != nil {
		return x.Since
	}
	return 0
}

func (x *NextResultsReq) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *NextResultsReq) GetWaitMs() int64 {
	if x != nil {
		return x.WaitMs
	}
	return 0
}

type NextResultsRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*LeafResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Next    uint64        `protobuf:"varint,2,opt,name=next,proto3" json:"next,omitempty"`
	Epoch   uint64        `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// treeDone reports that nothing will ever follow next. It travels with the
	// final results rather than being asked for separately, so that a caller
	// cannot learn a tree has finished before it has been handed everything the
	// tree produced.
	TreeDone  bool   `protobuf:"varint,4,opt,name=treeDone,proto3" json:"treeDone,omitempty"`
	TreeState string `protobuf:"bytes,5,opt,name=treeState,proto3" json:"treeState,omitempty"`
}

func (x *NextResultsRep) Reset() {
	*x = NextResultsRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valueprocs_proto_valueprocs_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NextResultsRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextResultsRep) ProtoMessage() {}

func (x *NextResultsRep) ProtoReflect() protoreflect.Message {
	mi := &file_valueprocs_proto_valueprocs_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextResultsRep.ProtoReflect.Descriptor instead.
func (*NextResultsRep) Descriptor() ([]byte, []int) {
	return file_valueprocs_proto_valueprocs_proto_rawDescGZIP(), []int{10}
}

func (x *NextResultsRep) GetResults() []*LeafResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *NextResultsRep) GetNext() uint64 {
	if x != nil {
		return x.Next
	}
	return 0
}

func (x *NextResultsRep) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *NextResultsRep) GetTreeDone() bool {
	if x != nil {
		return x.TreeDone
	}
	return false
}

func (x *NextResultsRep) GetTreeState() string {
	if x != nil {
		return x.TreeState
	}
	return ""
}

type TreeStatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TID string `protobuf:"bytes,1,opt,name=tID,proto3" json:"tID,omitempty"`
}

func (x *TreeStatusReq) Reset() {
	*x = TreeStatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valueprocs_proto_valueprocs_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TreeStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeStatusReq) ProtoMessage() {}

func (x *TreeStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_valueprocs_proto_valueprocs_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeStatusReq.ProtoReflect.Descriptor instead.
func (*TreeStatusReq) Descriptor() ([]byte, []int) {
	return file_valueprocs_proto_valueprocs_proto_rawDescGZIP(), []int{11}
}

func (x *TreeStatusReq) GetTID() string {
	if x != nil {
		return x.TID
	}
	return ""
}

// TreeStatusRep is a sample, not an event: latest wins, nothing is kept, and
// it carries no results. Results are collected with NextResults, which is
// what keeps this cheap enough to poll.
type TreeStatusRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TID             string        `protobuf:"bytes,1,opt,name=tID,proto3" json:"tID,omitempty"`
	Label           string        `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	State           string        `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Cancelled       bool          `protobuf:"varint,4,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	SubmittedUnixNs int64         `protobuf:"varint,5,opt,name=submittedUnixNs,proto3" json:"submittedUnixNs,omitempty"`
	NRunning        int32         `protobuf:"varint,6,opt,name=nRunning,proto3" json:"nRunning,omitempty"`
	NCharged        int32         `protobuf:"varint,7,opt,name=nCharged,proto3" json:"nCharged,omitempty"`
	Nodes           []*NodeStatus `protobuf:"bytes,8,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *TreeStatusRep) Reset() {
	*x = TreeStatusRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valueprocs_proto_valueprocs_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TreeStatusRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeStatusRep) ProtoMessage() {}

func (x *TreeStatusRep) ProtoReflect() protoreflect.Message {
	mi := &file_valueprocs_proto_valueprocs_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeStatusRep.ProtoReflect.Descriptor instead.
func (*TreeStatusRep) Descriptor() ([]byte, []int) {
	return file_valueprocs_proto_valueprocs_proto_rawDescGZIP(), []int{12}
}

func (x *TreeStatusRep) GetTID() string {
	if x != nil {
		return x.TID
	}
	return ""
}

func (x *TreeStatusRep) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *TreeStatusRep) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *TreeStatusRep) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

func (x *TreeStatusRep) GetSubmittedUnixNs() int64 {
	if x != nil {
		return x.SubmittedUnixNs
	}
	return 0
}

func (x *TreeStatusRep) GetNRunning() int32 {
	if x != nil {
		return x.NRunning
	}
	return 0
}

func (x *TreeStatusRep) GetNCharged() int32 {
	if x != nil {
		return x.NCharged
	}
	return 0
}

func (x *TreeStatusRep) GetNodes() []*NodeStatus {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type NodeStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeID    string `protobuf:"bytes,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Label     string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	State     string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	K         int32  `protobuf:"varint,4,opt,name=k,proto3" json:"k,omitempty"`
	NChildren int32  `protobuf:"varint,5,opt,name=nChildren,proto3" json:"nChildren,omitempty"`
	NRunning  int32  `protobuf:"varint,6,opt,name=nRunning,proto3" json:"nRunning,omitempty"`
	NCharged  int32  `protobuf:"varint,7,opt,name=nCharged,proto3" json:"nCharged,omitempty"`
	Target    int32  `protobuf:"varint,8,opt,name=target,proto3" json:"target,omitempty"`
	// Leaf-only below here.
	IsLeaf   bool    `protobuf:"varint,9,opt,name=isLeaf,proto3" json:"isLeaf,omitempty"`
	Workload string  `protobuf:"bytes,10,opt,name=workload,proto3" json:"workload,omitempty"`
	Run      uint64  `protobuf:"varint,11,opt,name=run,proto3" json:"run,omitempty"`
	RunState string  `protobuf:"bytes,12,opt,name=runState,proto3" json:"runState,omitempty"`
	Attempts int32   `protobuf:"varint,13,opt,name=attempts,proto3" json:"attempts,omitempty"`
	Stops    int32   `protobuf:"varint,14,opt,name=stops,proto3" json:"stops,omitempty"`
	Score    float64 `protobuf:"fixed64,15,opt,name=score,proto3" json:"score,omitempty"`
	Gradient float64 `protobuf:"fixed64,16,opt,name=gradient,proto3" json:"gradient,omitempty"`
	HasScore bool    `protobuf:"varint,17,opt,name=hasScore,proto3" json:"hasScore,omitempty"`
	// scoreStale reports that a running attempt has gone quiet. It is reported
	// and never acted on: an attempt that is compute-bound may simply not have
	// reached its next reporting point.
	ScoreStale bool   `protobuf:"varint,18,opt,name=scoreStale,proto3" json:"scoreStale,omitempty"`
	PID        string `protobuf:"bytes,19,opt,name=pID,proto3" json:"pID,omitempty"` // the current attempt's proc
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valueprocs_proto_valueprocs_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_valueprocs_proto_valueprocs_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_valueprocs_proto_valueprocs_proto_rawDescGZIP(), []int{13}
}

func (x *NodeStatus) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

func (x *NodeStatus) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *NodeStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *NodeStatus) GetK() int32 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *NodeStatus) GetNChildren() int32 {
	if x != nil {
		return x.NChildren
	}
	return 0
}

func (x *NodeStatus) GetNRunning() int32 {
	if x != nil {
		return x.NRunning
	}
	return 0
}

func (x *NodeStatus) GetNCharged() int32 {
	if x != nil {
		return x.NCharged
	}
	return 0
}

func (x *NodeStatus) GetTarget() int32 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *NodeStatus) GetIsLeaf() bool {
	if x != nil {
		return x.IsLeaf
	}
	return false
}

func (x *NodeStatus) GetWorkload() string {
	if x != nil {
		return x.Workload
	}
	return ""
}

func (x *NodeStatus) GetRun() uint64 {
	if x != nil {
		return x.Run
	}
	return 0
}

func (x *NodeStatus) GetRunState() string {
	if x != nil {
		return x.RunState
	}
	return ""
}

func (x *NodeStatus) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *NodeStatus) GetStops() int32 {
	if x != nil {
		return x.Stops
	}
	return 0
}

func (x *NodeStatus) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *NodeStatus) GetGradient() float64 {
	if x != nil {
		return x.Gradient
	}
	return 0
}

func (x *NodeStatus) GetHasScore() bool {
	if x != nil {
		return x.HasScore
	}
	return false
}

func (x *NodeStatus) GetScoreStale() bool {
	if x != nil {
		return x.ScoreStale
	}
	return false
}

func (x *NodeStatus) GetPID() string {
	if x != nil {
		return x.PID
	}
	return ""
}

type SchedStatsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SchedStatsReq) Reset() {
	*x = SchedStatsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valueprocs_proto_valueprocs_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchedStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedStatsReq) ProtoMessage() {}

func (x *SchedStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_valueprocs_proto_valueprocs_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedStatsReq.ProtoReflect.Descriptor instead.
func (*SchedStatsReq) Descriptor() ([]byte, []int) {
	return file_valueprocs_proto_valueprocs_proto_rawDescGZIP(), []int{14}
}

// SchedStatsRep explains the layer's behaviour from outside.
//
// pressure is reported alongside the terms it was folded from, because a bad
// pressure reading is the first thing to suspect when the layer misbehaves
// and it must be diagnosable without reading the code. The two counts are
// broken down by kind rather than totalled, since a flat total cannot answer
// "mostly pruning or mostly speculating?", which is the question the reasons
// exist for.
type SchedStatsRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pressure      float64            `protobuf:"fixed64,1,opt,name=pressure,proto3" json:"pressure,omitempty"`
	Busy          float64            `protobuf:"fixed64,2,opt,name=busy,proto3" json:"busy,omitempty"`
	DelayPressure float64            `protobuf:"fixed64,3,opt,name=delayPressure,proto3" json:"delayPressure,omitempty"`
	Components    map[string]float64 `protobuf:"bytes,4,rep,name=components,proto3" json:"components,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	NTrees        int32              `protobuf:"varint,5,opt,name=nTrees,proto3" json:"nTrees,omitempty"`
	NRunning      int32              `protobuf:"varint,6,opt,name=nRunning,proto3" json:"nRunning,omitempty"`
	NCharged      int32              `protobuf:"varint,7,opt,name=nCharged,proto3" json:"nCharged,omitempty"`
	Slots         int32              `protobuf:"varint,8,opt,name=slots,proto3" json:"slots,omitempty"`
	NStartsByKind map[uint32]int32   `protobuf:"bytes,9,rep,name=nStartsByKind,proto3" json:"nStartsByKind,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	NStopsByKind  map[uint32]int32   `protobuf:"bytes,10,rep,name=nStopsByKind,proto3" json:"nStopsByKind,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	NScoreDropped int32              `protobuf:"varint,11,opt,name=nScoreDropped,proto3" json:"nScoreDropped,omitempty"`
	// Below here the platform, not the scheduler: how well its decisions were
	// carried out. A nonzero nSynthesizedStopped is a bug report about a proc
	// that ignored its eviction, not normal operation.
	NSynthesizedStopped int64  `protobuf:"varint,12,opt,name=nSynthesizedStopped,proto3" json:"nSynthesizedStopped,omitempty"`
	NSynthesizedFailed  int64  `protobuf:"varint,13,opt,name=nSynthesizedFailed,proto3" json:"nSynthesizedFailed,omitempty"`
	NEvictRetries       int64  `protobuf:"varint,14,opt,name=nEvictRetries,proto3" json:"nEvictRetries,omitempty"`
	NUnrequestedEvicts  int64  `protobuf:"varint,15,opt,name=nUnrequestedEvicts,proto3" json:"nUnrequestedEvicts,omitempty"`
	Epoch               uint64 `protobuf:"varint,16,opt,name=epoch,proto3" json:"epoch,omitempty"`
}

func (x *SchedStatsRep) Reset() {
	*x = SchedStatsRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valueprocs_proto_valueprocs_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchedStatsRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedStatsRep) ProtoMessage() {}

func (x *SchedStatsRep) ProtoReflect() protoreflect.Message {
	mi := &file_valueprocs_proto_valueprocs_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedStatsRep.ProtoReflect.Descriptor instead.
func (*SchedStatsRep) Descriptor() ([]byte, []int) {
	return file_valueprocs_proto_valueprocs_proto_rawDescGZIP(), []int{15}
}

func (x *SchedStatsRep) GetPressure() float64 {
	if x != nil {
		return x.Pressure
	}
	return 0
}

func (x *SchedStatsRep) GetBusy() float64 {
	if x != nil {
		return x.Busy
	}
	return 0
}

func (x *SchedStatsRep) GetDelayPressure() float64 {
	if x != nil {
		return x.DelayPressure
	}
	return 0
}

func (x *SchedStatsRep) GetComponents() map[string]float64 {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *SchedStatsRep) GetNTrees() int32 {
	if x != nil {
		return x.NTrees
	}
	return 0
}

func (x *SchedStatsRep) GetNRunning() int32 {
	if x != nil {
		return x.NRunning
	}
	return 0
}

func (x *SchedStatsRep) GetNCharged() int32 {
	if x != nil {
		return x.NCharged
	}
	return 0
}

func (x *SchedStatsRep) GetSlots() int32 {
	if x != nil {
		return x.Slots
	}
	return 0
}

func (x *SchedStatsRep) GetNStartsByKind() map[uint32]int32 {
	if x != nil {
		return x.NStartsByKind
	}
	return nil
}

func (x *SchedStatsRep) GetNStopsByKind() map[uint32]int32 {
	if x != nil {
		return x.NStopsByKind
	}
	return nil
}

func (x *SchedStatsRep) GetNScoreDropped() int32 {
	if x != nil {
		return x.NScoreDropped
	}
	return 0
}

func (x *SchedStatsRep) GetNSynthesizedStopped() int64 {
	if x != nil {
		return x.NSynthesizedStopped
	}
	return 0
}

func (x *SchedStatsRep) GetNSynthesizedFailed() int64 {
	if x != nil {
		return x.NSynthesizedFailed
	}
	return 0
}

func (x *SchedStatsRep) GetNEvictRetries() int64 {
	if x != nil {
		return x.NEvictRetries
	}
	return 0
}

func (x *SchedStatsRep) GetNUnrequestedEvicts() int64 {
	if x != nil {
		return x.NUnrequestedEvicts
	}
	return 0
}

func (x *SchedStatsRep) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

var File_valueprocs_proto_valueprocs_proto protoreflect.FileDescriptor

var file_valueprocs_proto_valueprocs_proto_rawDesc = []byte{
	0x0a, 0x21, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x70, 0x72, 0x6f, 0x63, 0x73, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x70, 0x72, 0x6f, 0x63, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x70, 0x72, 0x6f, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x63, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a, 0x06, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x66, 0x12, 0x10,
	0x0a, 0x03, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x49, 0x44,
	0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x75, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x72, 0x75, 0x6e, 0x22, 0x7d, 0x0a, 0x08, 0x4e, 0x6f,
	0x64, 0x65, 0x53, 0x70, 0x65, 0x63, 0x12, 0x0c, 0x0a, 0x01, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x01, 0x6b, 0x12, 0x25, 0x0a, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x70, 0x65,
	0x63, 0x52, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x12, 0x26, 0x0a, 0x08, 0x6c,
	0x65, 0x61, 0x66, 0x50, 0x72, 0x6f, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x50, 0x72, 0x6f, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x08, 0x6c, 0x65, 0x61, 0x66, 0x50,
	0x72, 0x6f, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0x56, 0x0a, 0x0d, 0x53, 0x75, 0x62,
	0x6d, 0x69, 0x74, 0x54, 0x72, 0x65, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62,
	0x65, 0x6c, 0x12, 0x1d, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x72, 0x6f, 0x6f,
	0x74, 0x22, 0x21, 0x0a, 0x0d, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x54, 0x72, 0x65, 0x65, 0x52,
	0x65, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x74, 0x49, 0x44, 0x22, 0x21, 0x0a, 0x0d, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x72,
	0x65, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x74, 0x49, 0x44, 0x22, 0x1f, 0x0a, 0x0d, 0x43, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x54, 0x72, 0x65, 0x65, 0x52, 0x65, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x4b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x4b, 0x22, 0x5d, 0x0a, 0x0e, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x03, 0x72, 0x65,
	0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x66,
	0x52, 0x03, 0x72, 0x65, 0x66, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x67,
	0x72, 0x61, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x67,
	0x72, 0x61, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x20, 0x0a, 0x0e, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x4b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x4b, 0x22, 0x6f, 0x0a, 0x0a, 0x4c, 0x65, 0x61,
	0x66, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x03, 0x72, 0x65, 0x66,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x66, 0x52,
	0x03, 0x72, 0x65, 0x66, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72,
	0x6f, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a,
	0x70, 0x72, 0x6f, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x66, 0x0a, 0x0e, 0x4e, 0x65,
	0x78, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x49, 0x44, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x73,
	0x69, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x61,
	0x69, 0x74, 0x4d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x77, 0x61, 0x69, 0x74,
	0x4d, 0x73, 0x22, 0x9b, 0x01, 0x0a, 0x0e, 0x4e, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x52, 0x65, 0x70, 0x12, 0x25, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x4c, 0x65, 0x61, 0x66, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x6e, 0x65, 0x78, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x72, 0x65, 0x65, 0x44, 0x6f,
	0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x74, 0x72, 0x65, 0x65, 0x44, 0x6f,
	0x6e, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x72, 0x65, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x72, 0x65, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x22, 0x21, 0x0a, 0x0d, 0x54, 0x72, 0x65, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x74, 0x49, 0x44, 0x22, 0xf0, 0x01, 0x0a, 0x0d, 0x54, 0x72, 0x65, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x74, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65,
	0x64, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x55, 0x6e,
	0x69, 0x78, 0x4e, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x73, 0x75, 0x62, 0x6d,
	0x69, 0x74, 0x74, 0x65, 0x64, 0x55, 0x6e, 0x69, 0x78, 0x4e, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6e,
	0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6e,
	0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x43, 0x68, 0x61, 0x72,
	0x67, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6e, 0x43, 0x68, 0x61, 0x72,
	0x67, 0x65, 0x64, 0x12, 0x21, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x08, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0xe0, 0x03, 0x0a, 0x0a, 0x4e, 0x6f, 0x64, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x6b, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x43, 0x68, 0x69, 0x6c,
	0x64, 0x72, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6e, 0x43, 0x68, 0x69,
	0x6c, 0x64, 0x72, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e,
	0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6e, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e,
	0x67, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x64, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x6e, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x4c, 0x65, 0x61, 0x66, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x4c, 0x65, 0x61, 0x66, 0x12, 0x1a, 0x0a,
	0x08, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x75, 0x6e,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x72, 0x75, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x75, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72,
	0x75, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x74, 0x74, 0x65, 0x6d,
	0x70, 0x74, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x61, 0x74, 0x74, 0x65, 0x6d,
	0x70, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x70, 0x73, 0x18, 0x0e, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x70, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x67, 0x72, 0x61, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x10, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x08, 0x67, 0x72, 0x61, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x68,
	0x61, 0x73, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x11, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x68,
	0x61, 0x73, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x53, 0x74, 0x61, 0x6c, 0x65, 0x18, 0x12, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x53, 0x74, 0x61, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x49, 0x44, 0x18, 0x13,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x49, 0x44, 0x22, 0x0f, 0x0a, 0x0d, 0x53, 0x63, 0x68,
	0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x22, 0xd0, 0x06, 0x0a, 0x0d, 0x53,
	0x63, 0x68, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x70, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x72, 0x65, 0x73, 0x73, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08,
	0x70, 0x72, 0x65, 0x73, 0x73, 0x75, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x75, 0x73, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x62, 0x75, 0x73, 0x79, 0x12, 0x24, 0x0a, 0x0d,
	0x64, 0x65, 0x6c, 0x61, 0x79, 0x50, 0x72, 0x65, 0x73, 0x73, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x0d, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x50, 0x72, 0x65, 0x73, 0x73, 0x75,
	0x72, 0x65, 0x12, 0x3e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x52, 0x65, 0x70, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x54, 0x72, 0x65, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x6e, 0x54, 0x72, 0x65, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x52,
	0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6e, 0x52,
	0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x43, 0x68, 0x61, 0x72, 0x67,
	0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6e, 0x43, 0x68, 0x61, 0x72, 0x67,
	0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x12, 0x47, 0x0a, 0x0d, 0x6e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x73, 0x42, 0x79, 0x4b, 0x69, 0x6e, 0x64, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x70, 0x2e,
	0x4e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x73, 0x42, 0x79, 0x4b, 0x69, 0x6e, 0x64, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x0d, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x73, 0x42, 0x79, 0x4b, 0x69, 0x6e,
	0x64, 0x12, 0x44, 0x0a, 0x0c, 0x6e, 0x53, 0x74, 0x6f, 0x70, 0x73, 0x42, 0x79, 0x4b, 0x69, 0x6e,
	0x64, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x70, 0x2e, 0x4e, 0x53, 0x74, 0x6f, 0x70, 0x73, 0x42, 0x79,
	0x4b, 0x69, 0x6e, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c, 0x6e, 0x53, 0x74, 0x6f, 0x70,
	0x73, 0x42, 0x79, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x6e, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x44, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d,
	0x6e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x44, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x12, 0x30, 0x0a,
	0x13, 0x6e, 0x53, 0x79, 0x6e, 0x74, 0x68, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x64, 0x53, 0x74, 0x6f,
	0x70, 0x70, 0x65, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x13, 0x6e, 0x53, 0x79, 0x6e,
	0x74, 0x68, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x64, 0x53, 0x74, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x12,
	0x2e, 0x0a, 0x12, 0x6e, 0x53, 0x79, 0x6e, 0x74, 0x68, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x64, 0x46,
	0x61, 0x69, 0x6c, 0x65, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x6e, 0x53, 0x79,
	0x6e, 0x74, 0x68, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x64, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x12,
	0x24, 0x0a, 0x0d, 0x6e, 0x45, 0x76, 0x69, 0x63, 0x74, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x73,
	0x18, 0x0e, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x6e, 0x45, 0x76, 0x69, 0x63, 0x74, 0x52, 0x65,
	0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x12, 0x6e, 0x55, 0x6e, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x65, 0x64, 0x45, 0x76, 0x69, 0x63, 0x74, 0x73, 0x18, 0x0f, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x12, 0x6e, 0x55, 0x6e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x45,
	0x76, 0x69, 0x63, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x10,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x1a, 0x3d, 0x0a, 0x0f, 0x43,
	0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x40, 0x0a, 0x12, 0x4e, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x73, 0x42, 0x79, 0x4b, 0x69, 0x6e, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x3f, 0x0a, 0x11,
	0x4e, 0x53, 0x74, 0x6f, 0x70, 0x73, 0x42, 0x79, 0x4b, 0x69, 0x6e, 0x64, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x1a, 0x5a,
	0x18, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x6f, 0x73, 0x2f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x70, 0x72,
	0x6f, 0x63, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_valueprocs_proto_valueprocs_proto_rawDescOnce sync.Once
	file_valueprocs_proto_valueprocs_proto_rawDescData = file_valueprocs_proto_valueprocs_proto_rawDesc
)

func file_valueprocs_proto_valueprocs_proto_rawDescGZIP() []byte {
	file_valueprocs_proto_valueprocs_proto_rawDescOnce.Do(func() {
		file_valueprocs_proto_valueprocs_proto_rawDescData = protoimpl.X.CompressGZIP(file_valueprocs_proto_valueprocs_proto_rawDescData)
	})
	return file_valueprocs_proto_valueprocs_proto_rawDescData
}

var file_valueprocs_proto_valueprocs_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_valueprocs_proto_valueprocs_proto_goTypes = []interface{}{
	(*RunRef)(nil),         // 0: RunRef
	(*NodeSpec)(nil),       // 1: NodeSpec
	(*SubmitTreeReq)(nil),  // 2: SubmitTreeReq
	(*SubmitTreeRep)(nil),  // 3: SubmitTreeRep
	(*CancelTreeReq)(nil),  // 4: CancelTreeReq
	(*CancelTreeRep)(nil),  // 5: CancelTreeRep
	(*ReportScoreReq)(nil), // 6: ReportScoreReq
	(*ReportScoreRep)(nil), // 7: ReportScoreRep
	(*LeafResult)(nil),     // 8: LeafResult
	(*NextResultsReq)(nil), // 9: NextResultsReq
	(*NextResultsRep)(nil), // 10: NextResultsRep
	(*TreeStatusReq)(nil),  // 11: TreeStatusReq
	(*TreeStatusRep)(nil),  // 12: TreeStatusRep
	(*NodeStatus)(nil),     // 13: NodeStatus
	(*SchedStatsReq)(nil),  // 14: SchedStatsReq
	(*SchedStatsRep)(nil),  // 15: SchedStatsRep
	nil,                    // 16: SchedStatsRep.ComponentsEntry
	nil,                    // 17: SchedStatsRep.NStartsByKindEntry
	nil,                    // 18: SchedStatsRep.NStopsByKindEntry
	(*proc.ProcProto)(nil), // 19: ProcProto
}
var file_valueprocs_proto_valueprocs_proto_depIdxs = []int32{
	1,  // 0: NodeSpec.children:type_name -> NodeSpec
	19, // 1: NodeSpec.leafProc:type_name -> ProcProto
	1,  // 2: SubmitTreeReq.root:type_name -> NodeSpec
	0,  // 3: ReportScoreReq.ref:type_name -> RunRef
	0,  // 4: LeafResult.ref:type_name -> RunRef
	8,  // 5: NextResultsRep.results:type_name -> LeafResult
	13, // 6: TreeStatusRep.nodes:type_name -> NodeStatus
	16, // 7: SchedStatsRep.components:type_name -> SchedStatsRep.ComponentsEntry
	17, // 8: SchedStatsRep.nStartsByKind:type_name -> SchedStatsRep.NStartsByKindEntry
	18, // 9: SchedStatsRep.nStopsByKind:type_name -> SchedStatsRep.NStopsByKindEntry
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_valueprocs_proto_valueprocs_proto_init() }
func file_valueprocs_proto_valueprocs_proto_init() {
	if File_valueprocs_proto_valueprocs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_valueprocs_proto_valueprocs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_valueprocs_proto_valueprocs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_valueprocs_proto_valueprocs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitTreeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_valueprocs_proto_valueprocs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitTreeRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_valueprocs_proto_valueprocs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelTreeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_valueprocs_proto_valueprocs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelTreeRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_valueprocs_proto_valueprocs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportScoreReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_valueprocs_proto_valueprocs_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportScoreRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_valueprocs_proto_valueprocs_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeafResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_valueprocs_proto_valueprocs_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NextResultsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_valueprocs_proto_valueprocs_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NextResultsRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_valueprocs_proto_valueprocs_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TreeStatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_valueprocs_proto_valueprocs_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TreeStatusRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_valueprocs_proto_valueprocs_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_valueprocs_proto_valueprocs_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SchedStatsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_valueprocs_proto_valueprocs_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SchedStatsRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_valueprocs_proto_valueprocs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_valueprocs_proto_valueprocs_proto_goTypes,
		DependencyIndexes: file_valueprocs_proto_valueprocs_proto_depIdxs,
		MessageInfos:      file_valueprocs_proto_valueprocs_proto_msgTypes,
	}.Build()
	File_valueprocs_proto_valueprocs_proto = out.File
	file_valueprocs_proto_valueprocs_proto_rawDesc = nil
	file_valueprocs_proto_valueprocs_proto_goTypes = nil
	file_valueprocs_proto_valueprocs_proto_depIdxs = nil
}
