// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.33.0
// source: proxy/wasm/proto/wasmd.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	proc "sigmaos/proc"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunWASMProcReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Proc *proc.ProcProto `protobuf:"bytes,1,opt,name=proc,proto3" json:"proc,omitempty"`
}

func (x *RunWASMProcReq) Reset() {
	*x = RunWASMProcReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxy_wasm_proto_wasmd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunWASMProcReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunWASMProcReq) ProtoMessage() {}

func (x *RunWASMProcReq) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_wasm_proto_wasmd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunWASMProcReq.ProtoReflect.Descriptor instead.
func (*RunWASMProcReq) Descriptor() ([]byte, []int) {
	return file_proxy_wasm_proto_wasmd_proto_rawDescGZIP(), []int{0}
}

func (x *RunWASMProcReq) GetProc() *proc.ProcProto {
	if x != nil {
		return x.Proc
	}
	return nil
}

type RunWASMProcRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status uint64 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Err    string `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *RunWASMProcRep) Reset() {
	*x = RunWASMProcRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proxy_wasm_proto_wasmd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunWASMProcRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunWASMProcRep) ProtoMessage() {}

func (x *RunWASMProcRep) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_wasm_proto_wasmd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunWASMProcRep.ProtoReflect.Descriptor instead.
func (*RunWASMProcRep) Descriptor() ([]byte, []int) {
	return file_proxy_wasm_proto_wasmd_proto_rawDescGZIP(), []int{1}
}

func (x *RunWASMProcRep) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RunWASMProcRep) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *RunWASMProcRep) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_proxy_wasm_proto_wasmd_proto protoreflect.FileDescriptor

var file_proxy_wasm_proto_wasmd_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x77, 0x61, 0x73, 0x6d, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x77, 0x61, 0x73, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f,
	0x70, 0x72, 0x6f, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x30, 0x0a, 0x0e, 0x52, 0x75, 0x6e, 0x57, 0x41, 0x53, 0x4d, 0x50, 0x72, 0x6f, 0x63, 0x52, 0x65,
	0x71, 0x12, 0x1e, 0x0a, 0x04, 0x70, 0x72, 0x6f, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x04, 0x70, 0x72, 0x6f,
	0x63, 0x22, 0x4c, 0x0a, 0x0e, 0x52, 0x75, 0x6e, 0x57, 0x41, 0x53, 0x4d, 0x50, 0x72, 0x6f, 0x63,
	0x52, 0x65, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x10, 0x0a,
	0x03, 0x65, 0x72, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x42,
	0x1a, 0x5a, 0x18, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x6f, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x78, 0x79,
	0x2f, 0x77, 0x61, 0x73, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proxy_wasm_proto_wasmd_proto_rawDescOnce sync.Once
	file_proxy_wasm_proto_wasmd_proto_rawDescData = file_proxy_wasm_proto_wasmd_proto_rawDesc
)

func file_proxy_wasm_proto_wasmd_proto_rawDescGZIP() []byte {
	file_proxy_wasm_proto_wasmd_proto_rawDescOnce.Do(func() {
		file_proxy_wasm_proto_wasmd_proto_rawDescData = protoimpl.X.CompressGZIP(file_proxy_wasm_proto_wasmd_proto_rawDescData)
	})
	return file_proxy_wasm_proto_wasmd_proto_rawDescData
}

var file_proxy_wasm_proto_wasmd_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proxy_wasm_proto_wasmd_proto_goTypes = []interface{}{
	(*RunWASMProcReq)(nil), // 0: RunWASMProcReq
	(*RunWASMProcRep)(nil), // 1: RunWASMProcRep
	(*proc.ProcProto)(nil), // 2: ProcProto
}
var file_proxy_wasm_proto_wasmd_proto_depIdxs = []int32{
	2, // 0: RunWASMProcReq.proc:type_name -> ProcProto
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proxy_wasm_proto_wasmd_proto_init() }
func file_proxy_wasm_proto_wasmd_proto_init() {
	if File_proxy_wasm_proto_wasmd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proxy_wasm_proto_wasmd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunWASMProcReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proxy_wasm_proto_wasmd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunWASMProcRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proxy_wasm_proto_wasmd_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_wasm_proto_wasmd_proto_goTypes,
		DependencyIndexes: file_proxy_wasm_proto_wasmd_proto_depIdxs,
		MessageInfos:      file_proxy_wasm_proto_wasmd_proto_msgTypes,
	}.Build()
	File_proxy_wasm_proto_wasmd_proto = out.File
	file_proxy_wasm_proto_wasmd_proto_rawDesc = nil
	file_proxy_wasm_proto_wasmd_proto_goTypes = nil
	file_proxy_wasm_proto_wasmd_proto_depIdxs = nil
}
